config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
      resources :contacts
  end

  root 'contacts#index'
  resources :contacts do
    collection do
      get "download"
      get "upload"
      post "upload"
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :numbers, presence: true
  validates :name, presence: true
  validates :name, uniqueness: true
  serialize :numbers
  before_create :set_user_id

  self.per_page = 4
  USER_ID = 1
  NUMBER_TYPES = {
    :home   => "Home",
    :mobile => "Mobile",
    :office => "Office"
  }

  class << self
    def delete_contact(id)
      contact = Contact.find(id)
      return nil if contact.nil?
      
      contact.destroy 
      contact      
    end

    def update_contact(id, contact)
      rec = Contact.find(id)
      return nil if rec.nil?
      
      numbers = {}
        contact[:number_type].each_with_index do |typ, indx|
        numbers["#{typ}"] = contact[:number][indx]
      end

      rec.name = contact[:name]
      rec.numbers = numbers
      rec.save
      rec
    end
    
    def create_contact(name, number)
      contact = Contact.new(:name => name, :numbers => { :mobile => number })
      contact.save
      contact
    end
    
    def get_records(page=1, search=nil)
      page = page.to_i unless page.nil?
      results = Contact.where("user_id = ?", USER_ID)

      unless search.nil?
        results = results.where("LOWER(name) LIKE ?", "#{search.downcase}%")
      end

      results.page(page).order("name ASC")
    end

    def upload(file)
        spreadsheet = Roo::CSV.new(file.path)
        contacts = Contact.where("user_id = ?", USER_ID)
        new_names = []
        
        (2..spreadsheet.last_row).each do |i|
          name = spreadsheet.cell(i, 1).to_s.strip
          numbers = spreadsheet.cell(i, 2).to_s.strip.split(";")
          new_names << name.downcase
          
          Contact.create_from_csv(name, numbers)
        end
        
        #cleaning...
        unless new_names.empty?
          contacts.each do |contact|
            contact.destroy if !new_names.include? contact.name.downcase.strip
          end
        end
    end
    
    def to_csv(options = {})
      require 'csv'

      CSV.generate(options) do |csv|
        csv << ["Name", "Numbers"]
        all.each do |contact|
          num = []
          row = []
          row << contact.name

          contact.numbers.each_key do |k|
            num << "#{k.to_s} : " + contact.numbers[k].to_s
          end
          row << num.join(";")
          csv << row
        end
      end    
    end
    
    #numbers = ["mobile : 0142323444", " office: 032434344"]
    def create_from_csv(name, numbers)
      num_hash = {}
      records = where("LOWER(name) = ?", name.to_s.downcase.strip)

      numbers.each do |no|
        ntype, number = no.split(":")
        num_hash[ntype.downcase.strip.to_sym] = number.to_s.strip
      end
      
      if records.empty?
        Contact.create(:name => name.to_s.strip, :numbers => num_hash)
      else
        records.each do |contact|
          contact.update_contact_numbers(numbers)
        end
      end
    end

  end

  def primary_number
    return "" if numbers.nil? || numbers.empty?
    numbers[numbers.keys.first]
  end
  
  def update_contact_numbers(new_numbers=[])
    return if new_numbers.empty?
    num_hash = {}
    
    new_numbers.each do |no|
      ntype, number = no.split(":")
      num_hash[ntype.downcase.strip.to_sym] = number.to_s.strip
    end

    self.update_attribute(:numbers, num_hash) unless num_hash.empty?
  end
  
  def set_user_id
      self.user_id = USER_ID
  end
end

app/controllers/api/contacts_controller.rb
module Api
  class ContactsController < ApplicationController
    respond_to :json

    def index
      respond_with Contact.get_records(params[:page])
    end

    def show
      respond_with Contact.find(params[:id])
    end

    def create
      respond_with Contact.create_contact(params[:contact])
    end

    def update
      respond_with Contact.update_contact(params[:id], params[:contact])
    end

    def destroy
      respond_with Contact.destroy_contact(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :set_xhr_flash

  def set_xhr_flash
    flash.discard if request.xhr?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :json

  def upload    
    if request.post?
      Contact.upload(params[:file])
      redirect_to root_url, :notice => "Contacts successfully updated."
    end
  end
  
  def download
    @contacts = Contact.where("user_id=?", Contact::USER_ID)

    respond_to do |format|
      format.csv { send_data @contacts.to_csv }
    end
  end
  
  def index
    @contacts = Contact.get_records(params[:page], params[:q])
  end

  def edit
    @contact = Contact.find(params[:id])
  end
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create_contact(params[:contact][:name], params[:number])
  end

  def update
    @contact = Contact.update_contact(params[:id], params[:contact])
  end
  
  def destroy
    @contact = Contact.delete_contact(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def show_number_type(current_type='')
    html = "<select name=\"contact[number_type][]\" class=\"form-control\" style=\"width:80px;\">"
      Contact::NUMBER_TYPES.keys.each do |k|
        selected = (k.to_s == current_type.to_s) ? 'selected' : ''
        html += "<option value=\"#{k.to_s}\" #{selected}>#{Contact::NUMBER_TYPES[k]}</option>"
      end
    html += "</select>"

    raw(html)
  end
end

app/views/contacts/create.js.erb
<% if @contact.errors.empty? %>
  $(".form-container").empty();
  var html = '<div class="alert alert-success col-xs-3 "><small>Successfully created.</small></div>';
  $(".notice-container").empty();
  $(".notice-container").append(html).show().delay(1500).fadeOut();
  window.location="<%= root_url %>";
<% else %>
  var errors = "";
  <% @contact.errors.full_messages.each do |msg| %>
  errors += "<%= msg.to_s%>";
  <% end %>
  alert(errors);
<% end %>

app/views/contacts/destroy.js.erb
$(".contact-<%= @contact.id%>").fadeOut();

app/views/contacts/edit.js.erb
$(".form-container").empty();
var content = <%= render('contacts/edit').to_json.html_safe %>;
$(".form-container").html(content);

app/views/contacts/new.js.erb
$(".form-container").empty();
var content = <%= render('contacts/new').to_json.html_safe %>;
$(".form-container").html(content);

app/views/contacts/update.js.erb
<% if @contact.errors.empty? %>
  $(".edit-form").fadeOut();
  var html = '<div class="alert alert-success col-xs-3 "><small>Successfully updated.</small></div>';
  $(".notice-container").empty();
  $(".notice-container").append(html).show().delay(1000).fadeOut();
  $('#edit-contact-form')[0].reset();
  window.location="<%= root_url %>";
<% else %>
  var errors = "";
  <% @contact.errors.full_messages.each do |msg| %>
  errors += "<%= msg.to_s%>";
  <% end %>

  alert(errors);
<% end %>

app/views/contacts/upload.js.erb
$(".form-container").empty();
var content = <%= render('contacts/uploadform').to_json.html_safe %>;
$(".form-container").html(content);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <a href="<%= root_path %>"><h2> Phone Book </h2></a>

    <%= link_to "Add", new_contact_path, :remote => true %> |
    <%= link_to "Download", download_contacts_path(format: "csv") %> |
    <%= link_to "Upload", upload_contacts_path, :class => "upload-link", :remote => true %>
    <br/>

    <div class="notice-container">
      <% unless flash[:notice].nil?%>
        <div class="alert alert-success col-xs-3 ">
          <small><%= flash[:notice]%></small>
        </div>
      <% end %>
    </div>

    <%#= render "contacts/new"%>
    <div class="form-container"></div>

    <div class="clearfix"></div>
        
    <%= yield %>
  </div>
</div>
<script>
$(".alert-success").delay(2000).fadeOut();
</script>
</body>
</html>